# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"5\n\x0eWinrateRequest\x12\x12\n\nchamp_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x1f\n\x0cWinrateReply\x12\x0f\n\x07winrate\x18\x01 \x01(\x02\x32I\n\x08\x44\x61tabase\x12=\n\x07Winrate\x12\x18.database.WinrateRequest\x1a\x16.database.WinrateReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WINRATEREQUEST']._serialized_start=28
  _globals['_WINRATEREQUEST']._serialized_end=81
  _globals['_WINRATEREPLY']._serialized_start=83
  _globals['_WINRATEREPLY']._serialized_end=114
  _globals['_DATABASE']._serialized_start=116
  _globals['_DATABASE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
